# Mod properties
mod_version = 3.0.0
maven_group = com.zetplay
archives_base_name = zetplay

# Minecraft / Fabric
minecraft_version = 26.2
loader_version = 0.19.3

# Fabric API
fabric_version = 0.157.0+26.2

# Simple Voice Chat
voicechat_api_version = 2.6.20
voicechat_version = fabric-2.6.20+26.2
org.gradle.java.home=/usr/lib/jvm/java-25-openjdk-amd64
